const products = [
    {
        "id": 1,
        "title": "Oil Free Moisturizer 100ml",
        "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
        "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
        "price": 537  ,
        "discountPercentage": 13.1,
        "rating": 4.56,
        "stock": 88,
        "count": 745,
        "brand": "Dermive",
        "category": "skincare",
        "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
        "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
                   
}, {
    "id": 2,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
}, {
    "id": 3,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
}, 
   {
    "id": 4,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 5,
    "title": "Oil Free Moisturizer 100ml",
    "short_title":" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 6,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 7,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
}, 
{
    "id": 8,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 9,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 10,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},
{
    "id": 11,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},  
{
    "id": 12,
    "title": "Oil Free Moisturizer 100ml",
    "short_title" :" Moisturise & protect skin - For All Dry Skin Disorders",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 537,
    "discountPercentage": 13.1,
    "rating": 4.56,
    "stock": 88,
    "count": 745,
    "brand": "Dermive",
    "category": "skincare",
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "imagesURL":  "https://i.dummyjson.com/data/products/18/3.jpg",
               
},

    ]





module.exports = products;